const colorName = {
    white: "#FFFFFF",
    royalBlue: "#5064E2",
    dodgerBlue: "#2188FF",
    cornflowerBlue: "#4C98EF",
    black: "#000000",
    mineShaft: "#252525",
    slateGray: "#6E7E91",
    mercury: "#E5E5E5",
    iron: "#D1D5DA4D",
    seashell: "#F1F1F1",
    electricViolet: "#DF18FB",
    heliotrope: "#F18EFF",
    lavender: "#EB5DFF",
    mauve: "#F4A5FF",
    alto: "#D9D9D9", 
    doveGray: "#717171",
    silver: "#C9C9C9",
    guardsmanRed: "#D20000",
    torchRed: "#FB1B1B",
    gunPowder: "#42445A",
    codGray: "#171717",
    tundora: "#4b4b4b",
    manatee: "#8E8F97",
    tuna: "#33363F",
};

export const themeLight = {
    colors: {
        title: colorName.black,
        content: colorName.black,
        highLightedContent: colorName.electricViolet,
        bodyBackground: colorName.white, 
        header: {
            background: colorName.white,
            boxShadow: colorName.gunPowder,
        },
        hero: {
            background: colorName.black,
            content: colorName.white,
        },
        subHeader: {
            background: colorName.mineShaft,
            content: colorName.white,
            year: colorName.electricViolet,
        },
        logo: {
            main: colorName.royalBlue,
            hover: colorName.dodgerBlue,
            clicked: colorName.cornflowerBlue,
        },
        phone: {
            color: colorName.codGray,
        },
        themeSwitch: {
            background: colorName.mercury,
            border: colorName.slateGray,
            flickerBaground: colorName.slateGray,
        },
        navigation: {
            background: colorName.white,
            content: colorName.codGray,
            hover: colorName.royalBlue,
            active: colorName.royalBlue,
        },
        serviceList: {
            background: colorName.white,
            content: colorName.royalBlue,
            boxShadow: colorName.gunPowder,
            boxShadowHover: colorName.royalBlue,
        },
        footer: {
            background: colorName.mineShaft,
            content: colorName.white,
        },
        offerPage: {
            backgroundBox: colorName.white,
            title: colorName.royalBlue,
            content: colorName.black,
            border: colorName.electricViolet,
            itemContent: colorName.black,
        },
        linkButton: {
            content: colorName.white,
            background: colorName.royalBlue,
            boxShadow: colorName.mineShaft,
            backgroundHover: colorName.dodgerBlue,
            backgroundActive: colorName.dodgerBlue,
        },
        aboutPage: {
            title: colorName.black,
            content: colorName.black,
            border: colorName.royalBlue,
            subTitle: colorName.electricViolet,
        },
        dateTime: {
            content: colorName.black,
        },
        authorities: {
            background: colorName.alto,
            boxShadow: colorName.white,
        },
        linkIcon: {
            color: colorName.white,
            hover: colorName.electricViolet,
            active: colorName.heliotrope,
        },
        careerPage: {
            title: colorName.black,
            itemBackground: colorName.mineShaft,
            content: colorName.white,
            buttonBackground: colorName.electricViolet,
            buttonContent: colorName.white,
            buttonBackgroundHover: colorName.lavender,
            buttonBackgroundActive: colorName.mauve,
        },
        jobDetail: {
            containerBackground: colorName.seashell,
            title: colorName.black,
            content: colorName.black,
            jobName: colorName.electricViolet, 
            itemContent: colorName.black,
            buttonColor: colorName.white,
            button: colorName.royalBlue,
            buttonHover: colorName.dodgerBlue,
            buttonActive: colorName.cornflowerBlue,
        },
        applicatinForm: {
            background: colorName.seashell,
            title: colorName.black,
            border: colorName.alto,
            firm: colorName.royalBlue,
            content: colorName.black,
            backgroundForm: colorName.white,
            labelColor: colorName.doveGray,
            required: colorName.guardsmanRed,
            borderInput: colorName.silver,
            colorInput: colorName.doveGray,
        },
        formButton: {
            background: colorName.electricViolet,
            color: colorName.white,
            hover: colorName.lavender,
            active: colorName.mauve,
        },
        formSummary: {
            title: colorName.black,
            content: colorName.tuna,
            jobName: colorName.royalBlue,
            labelColor: colorName.black,
            borderInput: colorName.silver,
            colorInput: colorName.electricViolet,
            backgroundInput: colorName.white,
            required: colorName.guardsmanRed,
            acknowledgement: colorName.electricViolet,
            link: colorName.electricViolet,
            linkHover: colorName.lavender,
            linkActive: colorName.mauve,
        },
    }
};

export const themeDark = {
    colors: {
        title: colorName.white,
        content: colorName.white,
        highLightedContent: colorName.electricViolet,
        bodyBackground: colorName.mineShaft,
        header: {
            background: colorName.black,
            boxShadow: colorName.tundora,
        },
        hero: {
            background: colorName.black,
            content: colorName.white,
        },
        subHeader: {
            background: colorName.doveGray,
            content: colorName.white,
            year: colorName.electricViolet,
        },
        logo: {
            main: colorName.dodgerBlue,
            hover: colorName.royalBlue,
            clicked: colorName.cornflowerBlue,
        },
        phone: {
            color: colorName.white,
        },
        themeSwitch: {
            background: colorName.iron,
            border: colorName.white,
            flickerBaground: colorName.white,
        },
        navigation: {
            background: colorName.black,
            content: colorName.white,
            hover: colorName.dodgerBlue,
            active: colorName.dodgerBlue,
        },
        serviceList: {
            background: colorName.seashell,
            content: colorName.royalBlue,
            boxShadow: colorName.seashell,
            boxShadowHover: colorName.seashell,
        },
        footer: {
            background: colorName.black,
            content: colorName.white,
        },
        offerPage: {
            backgroundBox: colorName.seashell,
            title: colorName.royalBlue,
            content: colorName.white,
            border: colorName.electricViolet,
            itemContent: colorName.black,
        },
        linkButton: {
            content: colorName.white,
            background: colorName.royalBlue,
            boxShadow: colorName.mineShaft,
            backgroundHover: colorName.dodgerBlue,
            backgroundActive: colorName.dodgerBlue,
        },
        aboutPage: {
            title: colorName.white,
            content: colorName.white,
            border: colorName.dodgerBlue,
            subTitle: colorName.electricViolet,
        },
        dateTime: {
            content: colorName.white,
        },
        authorities: {
            background: colorName.alto,
            boxShadow: colorName.manatee,
        },
        linkIcon: {
            color: colorName.white,
            hover: colorName.electricViolet,
            active: colorName.heliotrope,
        },
        careerPage: {
            title: colorName.white,
            itemBackground: colorName.seashell,
            content: colorName.black,
            buttonBackground: colorName.electricViolet,
            buttonContent: colorName.white,
            buttonBackgroundHover: colorName.lavender,
            buttonBackgroundActive: colorName.mauve,
        },
        jobDetail: {
            containerBackground: colorName.doveGray,
            title: colorName.white,
            content: colorName.white,
            jobName: colorName.electricViolet, 
            itemContent: colorName.white,
            buttonColor: colorName.white,
            button: colorName.royalBlue,
            buttonHover: colorName.dodgerBlue,
            buttonActive: colorName.cornflowerBlue,
        },
        applicatinForm: {
            background: colorName.mineShaft,
            title: colorName.black,
            border: colorName.alto,
            firm: colorName.royalBlue,
            content: colorName.black,
            backgroundForm: colorName.white,
            labelColor: colorName.doveGray,
            required: colorName.guardsmanRed,
            borderInput: colorName.silver,
            colorInput: colorName.doveGray,
        },
        formButton: {
            background: colorName.electricViolet,
            color: colorName.white,
            hover: colorName.lavender,
            active: colorName.mauve,
        },
        formSummary: {
            title: colorName.white,
            content: colorName.white,
            jobName: colorName.dodgerBlue,
            labelColor: colorName.white,
            borderInput: colorName.silver,
            colorInput: colorName.electricViolet,
            backgroundInput: colorName.mineShaft,
            required: colorName.torchRed,
            acknowledgement: colorName.electricViolet,
            link: colorName.electricViolet,
            linkHover: colorName.lavender,
            linkActive: colorName.mauve,
        },
    },
};